import { Header } from '@/components/features/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AccountProvider } from '../context/AccountProvider';
import { PageProvider } from '@/context/PageProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PageProvider>
          <AccountProvider>
              <Header/>
              {children}
          </AccountProvider>
        </PageProvider>
        </body>
    </html>
  )
}
